#!/usr/bin/env python3
"""Regenerate src/shared/AssetIds.luau from tools/asset-import/upload-manifest.json.

Called by tools/scripts/upload-assets.sh after uploads, and by anyone who adds
rows to the manifest (e.g. tools/harness/seed_upload_rows.py). Idempotent:
running it twice produces the same file.

Rows are grouped by the category prefix of their key ("Sfx.WeaponFire" ->
category "Sfx", entry "WeaponFire"). assetId 0 stays the PLACEHOLDER so every
consumer's `AssetIds.isPlaceholder(...)` no-op path keeps working.

    python3 tools/scripts/regen-asset-ids.py            # write
    python3 tools/scripts/regen-asset-ids.py --check    # exit 1 if stale
"""
from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "tools" / "asset-import" / "upload-manifest.json"
OUT = ROOT / "src" / "shared" / "AssetIds.luau"

# Fixed category order so diffs stay readable; unknown categories append.
CATEGORY_ORDER = ["Icons", "Thumbs", "Images", "Music", "Sfx", "Ambient", "Skyboxes", "Textures", "Models"]

HEADER = """--!strict
--[[
	Outpost-7 — first-party asset ID manifest (single source of truth).

	AUTO-GENERATED by tools/scripts/regen-asset-ids.py from
	tools/asset-import/upload-manifest.json. Do NOT hand-edit ids here — add a
	row to the manifest (or run tools/harness/seed_upload_rows.py) and re-run
	the generator / the upload workflow.

	Every `rbxassetid://` the game loads for a first-party asset lives here —
	never a literal `rbxassetid://…` in a module (same rule as "no magic
	numbers", per CLAUDE.md). `rbxassetid://0` means "not uploaded yet";
	consumers treat it as a no-op via AssetIds.isPlaceholder.

	Categories:
	  Icons / Thumbs / Images — 2D listing, store, HUD art (Decal uploads)
	  Music / Sfx / Ambient   — audio (Audio uploads)
	  Skyboxes                — six faces per biome: <Biome><Ft|Bk|Lf|Rt|Up|Dn>
	  Textures                — particle / beam / decal / floor textures (Decal)
	  Models                  — FBX uploads (Model); loaded at boot by
	                            Server.World.ArtTemplateLoader into
	                            ServerStorage.ArtTemplates and attached to the
	                            procedural placeholders by Shared.Lib.VisualAttach
--]]

export type AssetManifest = { [string]: { [string]: string } }

local PLACEHOLDER = "rbxassetid://0"

local AssetIds = {
"""

FOOTER = """}

-- True when an id is still the unset placeholder. Consumers (AudioController,
-- BiomeLightingService, ArtTemplateLoader, HUD) use this to no-op cleanly on
-- a dev build instead of spawning a broken Sound / Sky / Image / Model.
function AssetIds.isPlaceholder(id: string?): boolean
	return id == nil or id == PLACEHOLDER or id == "rbxassetid://0" or id == "0"
end

return AssetIds
"""


def render(manifest: dict) -> str:
    cats: dict[str, dict[str, int]] = collections.OrderedDict()
    for _file, row in manifest["assets"].items():
        cat, _, name = row["key"].partition(".")
        if not name:
            raise SystemExit(f"bad key {row['key']!r}: expected Category.Name")
        cats.setdefault(cat, {})[name] = int(row.get("assetId", 0) or 0)
    ordered = [c for c in CATEGORY_ORDER if c in cats] + sorted(c for c in cats if c not in CATEGORY_ORDER)
    lines = [HEADER.rstrip("\n")]
    for cat in ordered:
        lines.append(f"\t{cat} = {{")
        for name in sorted(cats[cat]):
            asset_id = cats[cat][name]
            val = "PLACEHOLDER" if not asset_id else f'"rbxassetid://{asset_id}"'
            lines.append(f"\t\t{name} = {val},")
        lines.append("\t},")
    lines.append(FOOTER.rstrip("\n"))
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    text = render(manifest)
    if args.check:
        if OUT.exists() and OUT.read_text() == text:
            print("AssetIds.luau up to date")
            return 0
        print("::error::src/shared/AssetIds.luau is stale — run tools/scripts/regen-asset-ids.py")
        return 1
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({sum(1 for _ in manifest['assets'])} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
