#!/usr/bin/env bash
#
# Outpost-7 — Open Cloud asset uploader.
#
# Reads tools/asset-import/upload-manifest.json, uploads any asset whose file
# exists on disk but whose recorded assetId is still 0, records the returned
# id back into the manifest, and regenerates src/shared/AssetIds.luau.
#
# Roblox asset IDs are IMMUTABLE once issued, so this only uploads rows still
# at assetId 0 — re-running is safe and idempotent. Run it via the
# `upload-assets.yml` workflow (workflow_dispatch), not on every push.
#
# Env:
#   ROBLOX_API_KEY   required unless DRY_RUN=true — Open Cloud key with
#                    asset:read + asset:write on the target creator. Audio
#                    uploads also require the creator to be ID-verified.
#   ROBLOX_CREATOR_ID   the user or group id that will own the uploaded assets.
#   ROBLOX_CREATOR_TYPE "User" (default) or "Group".
#   DRY_RUN          "true" → print what would upload, mutate nothing.
#
# Reference: https://create.roblox.com/docs/cloud/guides/usage-assets
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MANIFEST="$ROOT/tools/asset-import/upload-manifest.json"
OUT_LUA="$ROOT/src/shared/AssetIds.luau"
API="https://apis.roblox.com/assets/v1/assets"

DRY_RUN="${DRY_RUN:-false}"
CREATOR_ID="${ROBLOX_CREATOR_ID:-0}"
CREATOR_TYPE="${ROBLOX_CREATOR_TYPE:-User}"

if [[ ! -f "$MANIFEST" ]]; then
  echo "::error::manifest not found at $MANIFEST"
  exit 1
fi

command -v jq >/dev/null 2>&1 || { echo "::error::jq is required"; exit 1; }

echo "== Outpost-7 asset upload =="
echo "manifest: $MANIFEST"
echo "dry_run:  $DRY_RUN"

# Iterate rows whose file exists and assetId == 0.
mapfile -t PENDING < <(jq -r '.assets | to_entries[] | select(.value.assetId == 0) | .key' "$MANIFEST")

if [[ ${#PENDING[@]} -eq 0 ]]; then
  echo "Nothing to upload — every manifest row already has an assetId."
fi

for FILE_REL in "${PENDING[@]}"; do
  FILE_ABS="$ROOT/$FILE_REL"
  KEY="$(jq -r --arg f "$FILE_REL" '.assets[$f].key' "$MANIFEST")"
  ASSET_TYPE="$(jq -r --arg f "$FILE_REL" '.assets[$f].assetType' "$MANIFEST")"

  if [[ ! -f "$FILE_ABS" ]]; then
    echo "  skip (no file yet): $FILE_REL  [$KEY]"
    continue
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  would upload: $FILE_REL  [$KEY, $ASSET_TYPE]"
    continue
  fi

  if [[ -z "${ROBLOX_API_KEY:-}" ]]; then
    echo "::error::ROBLOX_API_KEY is required for a real upload"
    exit 1
  fi

  echo "  uploading: $FILE_REL  [$KEY, $ASSET_TYPE]"
  REQUEST=$(jq -n \
    --arg at "$ASSET_TYPE" \
    --arg ct "$CREATOR_TYPE" \
    --arg cid "$CREATOR_ID" \
    --arg name "$KEY" \
    '{assetType:$at, displayName:$name, description:"Outpost-7 asset", creationContext:{creator:( ($ct=="Group") | if . then {groupId:($cid|tonumber)} else {userId:($cid|tonumber)} end )}}')

  # Multipart: the JSON "request" part + the binary "fileContent" part.
  RESPONSE=$(curl --fail-with-body --silent --show-error \
    -X POST "$API" \
    -H "x-api-key: $ROBLOX_API_KEY" \
    -F "request=$REQUEST" \
    -F "fileContent=@$FILE_ABS")

  # The upload returns a long-running operation; poll it for the assetId.
  OP_PATH=$(echo "$RESPONSE" | jq -r '.path // empty')
  ASSET_ID=$(echo "$RESPONSE" | jq -r '.response.assetId // empty')

  if [[ -z "$ASSET_ID" && -n "$OP_PATH" ]]; then
    for _ in $(seq 1 30); do
      sleep 2
      OP=$(curl --fail-with-body --silent --show-error \
        -H "x-api-key: $ROBLOX_API_KEY" \
        "https://apis.roblox.com/assets/v1/$OP_PATH")
      ASSET_ID=$(echo "$OP" | jq -r '.response.assetId // empty')
      [[ -n "$ASSET_ID" ]] && break
    done
  fi

  if [[ -z "$ASSET_ID" ]]; then
    echo "::error::no assetId returned for $FILE_REL — response: $RESPONSE"
    exit 1
  fi

  echo "    → assetId $ASSET_ID"
  # Record it back into the manifest (atomic write).
  TMP="$(mktemp)"
  jq --arg f "$FILE_REL" --argjson id "$ASSET_ID" '.assets[$f].assetId = $id' "$MANIFEST" > "$TMP"
  mv "$TMP" "$MANIFEST"
done

# --- Regenerate src/shared/AssetIds.luau from the manifest --------------------
# Groups rows by the category prefix of their key (e.g. "Sfx.WeaponFire" →
# category "Sfx", entry "WeaponFire"). assetId 0 stays as the placeholder.
echo "Regenerating $OUT_LUA"
python3 - "$MANIFEST" "$OUT_LUA" <<'PY'
import json, sys, collections

manifest_path, out_path = sys.argv[1], sys.argv[2]
with open(manifest_path) as f:
    manifest = json.load(f)

cats = collections.OrderedDict()
for _file, row in manifest["assets"].items():
    cat, _, name = row["key"].partition(".")
    cats.setdefault(cat, {})[name] = row["assetId"]

def rbx(asset_id):
    return f'rbxassetid://{asset_id}' if asset_id else 'rbxassetid://0'

lines = []
lines.append('--!strict')
lines.append('-- AUTO-GENERATED by tools/scripts/upload-assets.sh from')
lines.append('-- tools/asset-import/upload-manifest.json. Do NOT hand-edit the')
lines.append('-- ids here — add rows to the manifest and re-run the upload workflow.')
lines.append('-- The isPlaceholder helper + the header docs live in the hand-authored')
lines.append('-- seed; this generator preserves the category/PLACEHOLDER shape.')
lines.append('')
lines.append('export type AssetManifest = { [string]: { [string]: string } }')
lines.append('')
lines.append('local PLACEHOLDER = "rbxassetid://0"')
lines.append('')
lines.append('local AssetIds = {')
for cat, entries in cats.items():
    lines.append(f'\t{cat} = {{')
    for name, asset_id in entries.items():
        val = 'PLACEHOLDER' if not asset_id else f'"{rbx(asset_id)}"'
        lines.append(f'\t\t{name} = {val},')
    lines.append('\t},')
lines.append('}')
lines.append('')
lines.append('function AssetIds.isPlaceholder(id: string?): boolean')
lines.append('\treturn id == nil or id == PLACEHOLDER or id == "rbxassetid://0" or id == "0"')
lines.append('end')
lines.append('')
lines.append('return AssetIds')

with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {out_path}")
PY

echo "== done =="
